music = {
    "Chogada": "https://www.youtube.com/watch?v=yr7JFNsz5dU&list=RDyr7JFNsz5dU&start_radio=1",
    "Shubhaarambh": "https://www.youtube.com/watch?v=22MO_iJIQoM&list=RD22MO_iJIQoM&start_radio=1",
    "Nagada Sang Dhol": "https://www.youtube.com/watch?v=3X7x4Ye-tqo&list=RD3X7x4Ye-tqo&start_radio=1", 
    "Kamariya": "https://www.youtube.com/watch?v=i0_m90T04uw&list=RDi0_m90T04uw&start_radio=1",
    "Khalasi": "https://www.youtube.com/watch?v=t7wSjy9Lv-o&list=RDt7wSjy9Lv-o&start_radio=1",
    "Rangilo Maro Dholna": "https://www.youtube.com/watch?v=2bp7zdzWj3Y&list=RD2bp7zdzWj3Y&start_radio=1", 
    "Mann Melo": "https://www.youtube.com/watch?v=PsD23d5KdJI&list=RDPsD23d5KdJI&start_radio=1",
    "Sanedo": "https://www.youtube.com/watch?v=fT6Q5Ubd9Js&list=RDfT6Q5Ubd9Js&start_radio=1",            
    "Udi Udi Jaye": "https://www.youtube.com/watch?v=YZV0birVI-o&list=RDYZV0birVI-o&start_radio=1",
    "Vhalam Aavo Ne": "https://www.youtube.com/watch?v=k4whtZSnvMs&list=RDk4whtZSnvMs&start_radio=1",
    "Mor Bani Thanghat Kare": "https://www.youtube.com/watch?v=xJsvTCMg0qA&list=RDxJsvTCMg0qA&start_radio=1",
    "Odhani Odhu Ne": "https://www.youtube.com/watch?v=h94Py-rFDvA&list=RDh94Py-rFDvA&start_radio=1",
    "Jai Jai Shivshankar": "https://www.youtube.com/watch?v=oGneAab3e88&list=RDoGneAab3e88&start_radio=1",
    "Kar Har Maidan Fateh": "https://www.youtube.com/watch?v=9iIX4PBplAY&list=RD9iIX4PBplAY&start_radio=1",
    "Naacho Naacho": "https://www.youtube.com/watch?v=sAzlWScHTc4&list=RDsAzlWScHTc4&start_radio=1",
    "Aala Re Aala": "https://www.youtube.com/watch?v=tKBa64-w4XA&list=RDtKBa64-w4XA&start_radio=1",
    "Malhari": "https://www.youtube.com/watch?v=sRlA7JWTj04&list=RDsRlA7JWTj04&start_radio=1",
    "What Jhumka": "https://www.youtube.com/watch?v=P1fIdFRnfqw&list=RDP1fIdFRnfqw&start_radio=1",
    "Chhaiya Chhaiya": "https://www.youtube.com/watch?v=PimKrn3XkuU&list=RDPimKrn3XkuU&start_radio=1",
    "Malang": "https://www.youtube.com/watch?v=KBIq11mNB0I&list=RDKBIq11mNB0I&start_radio=1",
    "Nashe Si Chadh Gayi": "https://www.youtube.com/watch?v=HoCwa6gnmM0&list=RDHoCwa6gnmM0&start_radio=1",
    "Dance Ka Bhoot": "https://www.youtube.com/watch?v=mbN9MHQ0ZTU&list=RDmbN9MHQ0ZTU&start_radio=1",
    "Lungi Dance": "https://www.youtube.com/watch?v=IZL6aoVJu2M&list=RDIZL6aoVJu2M&start_radio=1",
    "Jai Ho": "https://www.youtube.com/watch?v=uinBpHT-AxM&list=RDuinBpHT-AxM&start_radio=1"
}
